[package]
name = "kitty-genetic-alg-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.kitty-genetic-alg]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.1.9"
path = "../../../../../framework/meta"
